### ndarray对象

In [1]:
import numpy as np

In [ ]:
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)
# object 数组
# dtype 数据类型
# copy 是否需要复制
# order 数组样式，c为反方向，F为列方向，A为任意
# subok 默认返回一个与基类类型一致的数组
# ndmin 指定生成数组的最小维度

In [2]:
a = np.array([1,2,3])
print (a)

[1 2 3]


In [3]:
a = np.array([[1,2],[3,4]])
print (a)

[[1 2]
 [3 4]]


In [4]:
# 最小维度  
a = np.array([1, 2, 3, 4, 5], ndmin =  2)  
print (a)

[[1 2 3 4 5]]


In [5]:
# dtype 参数  
import numpy as np 
a = np.array([1,  2,  3], dtype = complex)  
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# 使用标量类型
dt = np.dtype(np.int32)
print(dt)

int32


In [7]:
# int8, int16, int32, int64 四种数据类型可以使用字符串 'i1', 'i2','i4','i8' 代替
dt = np.dtype('i4')
print(dt)

int32


In [8]:
# 将数据类型应用于 ndarray 对象
import numpy as np
dt = np.dtype([('age',np.int8)]) 
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)

[(10,) (20,) (30,)]


In [11]:
a = np.arange(24)  
print (a.ndim)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)  # b 现在拥有三个维度
print (b.ndim)

1
3


In [15]:
print("a=", a, "\n")
print("b=", b)

a= [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23] 

b= [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [16]:
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)
a.shape =  (3,2)  
print (a)

(2, 3)
[[1 2]
 [3 4]
 [5 6]]


In [18]:
# itemsize返回数组每一个元素大小
# 数组的 dtype 为 int8（一个字节）  
x = np.array([1,2,3,4,5], dtype = np.int8)  
print (x.itemsize)
 
# 数组的 dtype 现在为 float64（八个字节） 
y = np.array([1,2,3,4,5], dtype = np.float64)  
print (y.itemsize)

1
8


### 数据类型

In [19]:
# 创建空数组
x = np.empty([3,2], dtype=int)
print (x)

[[0 0]
 [0 0]
 [0 0]]


In [22]:
# 创建指定大小数组， 所有元素填充0
np.zeros([3,2], dtype=float, order='C')

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [23]:
# 默认为浮点数
x = np.zeros(5) 
print(x)
 
# 设置类型为整数
y = np.zeros((5,), dtype = int) 
print(y)
 
# 自定义类型
z = np.zeros((2,2), dtype = [('x', 'i4'), ('y', 'i4')])  
print(z)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [25]:
# 创建指定形状的数组，数组元素以 1 来填充

# 默认为浮点数
x = np.ones(5) 
print(x)
 
# 自定义类型
x = np.ones([2,2], dtype = int)
print(x)

[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]


In [ ]:
# 创建相同形状的数组
# 填充0
numpy.zeros_like(a, dtype=None, order='K', subok=True, shape=None)
# 填充1
numpy.ones_like(a, dtype=None, order='K', subok=True, shape=None)

In [26]:
# 从已有数组创建np数组
# 列表->ndarray
x =  [1,2,3] 
a = np.asarray(x)  
print (a)

# 元组->ndarray
x =  (1,2,3) 
a = np.asarray(x)  
print (a)

[1 2 3]
[1 2 3]


In [29]:
# np.arrange 从数值范围创建数组

# 生成 0 到 4 长度为 5 的数组:
x = np.arange(5)  
print (x)

# 设置了起始值、终止值及步长：
x = np.arange(10,20,2)  
print (x)

[0 1 2 3 4]
[10 12 14 16 18]


In [ ]:
# numpy.linspace 函数用于创建一个一维数组，数组是一个等差数列构成的，格式如下：
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [30]:
# 设置起始点为 1 ，终止点为 10，数列个数为 10
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [31]:
a =np.linspace(1,10,10,retstep= True)
 
print(a)
# 拓展例子
b =np.linspace(1,10,10).reshape([10,1])
print(b)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), np.float64(1.0))
[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [ ]:
# numpy.logspace 函数用于创建一个于等比数列
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
# 底数默认为10

In [32]:
a = np.logspace(1.0,  2.0, num =  10)  # a为起始10，终点100，由十个数组成的等比数列
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


### 切片和索引

In [37]:
a = np.arange(10)
s = slice(2, 7, 2) # 从索引2开始到7结束，间隔为2
print (a)
print (a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [47]:
b = np.arange(1,10,1).reshape(3,3)
print(b)
print(b[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [49]:
# 显示指定行、列元素
print (b[1, ...]) # 显示第二行
print (b[..., 1]) # 显示第二列
print (b[..., 1:]) # 显示第二列及以后

[4 5 6]
[2 5 8]
[[2 3]
 [5 6]
 [8 9]]
